version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: admin
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: bot
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
  redis:
    image: redis
