version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ishvara-db-data:/var/lib/postgresql/data
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - redis
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
    restart: always
    depends_on:
      - db
  redis:
    image: redis

volumes:
  ishvara-db-data:
    name: ishvara-db-data